# Generated by Django 2.1.1 on 2018-09-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='FullName',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
